# Generated by Django 4.0.2 on 2022-02-09 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('inserted_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('name', models.CharField(default='', max_length=30)),
                ('symbol', models.CharField(default='', max_length=30)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('market_cap', models.BigIntegerField(default=0.0, null=True)),
                ('market_cap_dominance', models.BigIntegerField(default=0.0, null=True)),
                ('fully_diluted_market_cap', models.BigIntegerField(default=0.0, null=True)),
                ('percent_change_1h', models.FloatField(default=0.0, null=True)),
                ('percent_change_24h', models.FloatField(default=0.0, null=True)),
                ('percent_change_30d', models.FloatField(default=0.0, null=True)),
                ('percent_change_60d', models.FloatField(default=0.0, null=True)),
                ('percent_change_7d', models.FloatField(default=0.0, null=True)),
                ('percent_change_90d', models.FloatField(default=0.0, null=True)),
                ('volume_24h', models.FloatField(default=0.0, null=True)),
                ('volume_change_24h', models.FloatField(default=0.0, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'inserted_at')},
            },
        ),
    ]
